language: python

addons:
  apt:
    sources:
    - sourceline: deb http://software.ligo.org/lscsoft/debian wheezy contrib
      key_url: http://software.ligo.org/keys/deb/lscsoft.key
    - sourceline: deb-src http://software.ligo.org/lscsoft/debian wheezy contrib
      key_url: http://software.ligo.org/keys/deb/lscsoft.key
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - swig
    - pkg-config
    - zlib1g-dev
    - libgsl0-dev
    - swig
    - bc
    - libfftw3-dev

python:
- '2.7'
- '3.5'

env:
  global:
  - LAL_VERSION="6.18.0"
  - KERAS_BACKEND=theano
  matrix:
  - PIP_FLAGS="--quiet"
  - PIP_FLAGS="--quiet --pre"

matrix:
  allow_failures:
  - python: '3.5'
  fast_finish: true

before_install:
- pip install -q --upgrade pip
- pip install ${PRE} -r requirements.txt
- .travis/build-lal.sh

install:
- pip install --editable . 

before_script:
- pip list installed

script:
- pip install ${PRE} unittest2 coveralls "pytest>=2.8"
- . .travis/run-tests.sh

after_success:
- coveralls

cache:
  apt: true
  pip: true
  directories:
  - lal-${LAL_VERSION}
